[package]
name = "playground-wgpu"
version = "0.1.0"
authors = ["Robin Mattheussen <robin.mattheussen@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.4"
image = "0.22"
wgpu = "0.5.0"
winit = "0.20"