[package]
name = "playground-wgpu"
version = "0.1.0"
authors = ["Robin Mattheussen <robin.mattheussen@gmail.com>"]
edition = "2018"

[dependencies]
bytemuck = "1.2.0"
futures = "0.3.4"
glsl-to-spirv = "0.1"
image = "0.22"
wgpu = "0.5.0"
winit = "0.20"